---
apiVersion: v2
appVersion: 2.0.23
version: 1.0.0
name: gotify
description: a simple server for sending and receiving messages
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/gotify"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - server
  - gotify
  - messages
icon: https://gotify.net/img/logo.png
sources:
  - https://gotify.net/
  - https://github.com/gotify/server
  - https://hub.docker.com/r/gotify/server
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump common to 0.1.13
    - kind: changed
      description: Bump tag to 2.0.23
    - kind: changed
      description: Simplify values.yaml
  artifacthub.io/images: |
    - name: gotify
      image: gotify/server-arm7:2.0.23
