---
apiVersion: v2
appVersion: "7.3.0"
version: 1.0.0
name: digikam
description: Professional Photo Management with the Power of Open Source
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/digikam"
icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/digikam.png"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - digikam
  - photo
  - management
  - image
  - gallery
sources:
  - https://github.com/linuxserver/docker-digikam
  - https://www.digikam.org/
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump tag to version-7.3.0
  artifacthub.io/images: |
    - name: digikam
      image: ghcr.io/linuxserver/digikam:version-7.3.0
