---
# Default values for leantime.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: ghcr.io/nicholaswilde/leantime
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.1.7-ls6"

secret: {}
  # LEAN_DB_USER: "admin"
  # LEAN_DB_PASSWORD: "321.qwerty"

env:
  # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  TZ: "America/Los_Angeles"
  # LEAN_DB_HOST: "mysql_leantime"
  # LEAN_DB_DATABASE: "leantime"

service:
  port:
    port: 80
  additionalPorts:
    - name: "9000-udp"
      port: 9000

ingress:
  enabled: true
  hosts:
    - host: "leantime.192.168.1.203.nip.io"
      paths:
        - path: /
          # Ignored if not kubeVersion >= 1.14-0
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  sessions:
    enabled: false
    emptyDir: false
    mountPath: /sessions
    ## Template downloads data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    ##
    ## If you want to reuse an existing claim, you can pass the name of the PVC using
    ## the existingClaim variable
    # existingClaim: your-claim
    accessMode: ReadWriteOnce
    size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    skipuninstall: false

#probes:
#  liveness:
#    enabled: false
#  readiness:
#    enabled: false
