---
apiVersion: v2
name: common
description: Function library for nicholaswilde's helm charts
type: library
version: 0.1.12
keywords:
  - nicholaswilde
  - common
home: https://github.com/nicholaswilde/helm-charts/tree/master/charts/common
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Removed required objects from values.schema.json
