---
apiVersion: v2
appVersion: "0.13.1"
version: 1.0.0
name: writefreely
description: A simple, federated blogging platform.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/writefreely"
icon: "https://avatars.githubusercontent.com/u/45876560?s=200&v=4"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - writefreely
  - blog
sources:
  - https://github.com/writefreely/writefreely
  - https://github.com/nicholaswilde/docker-writefreely
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial release.
  artifacthub.io/images: |
    - name: writefreely
      image: ghcr.io/nicholaswilde/writefreely:version-0.13.1
