---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/blob/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/linuxserver/papermerge
  pullPolicy: IfNotPresent
  tag: "v2.0.1-ls6"

# See more environment variables in the papermerge documentation
# https://papermerge.com/docs/Installation/settings.html
# https://github.com/linuxserver/docker-papermerge
env: {}
  # TZ: ""

service:
  port:
    port: 8000

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config
  data:
    enabled: false
    emptyDir: false
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 1Gi

# Enabled mariadb
# ... for more options see https://github.com/nicholaswilde/helm-charts/blob/main/charts/mariadb/values.yaml
mariadb:
  enabled: false
  secret:
    MYSQL_ROOT_PASSWORD: "papermerge-pass"
    MYSQL_PASSWORD: "papermerge-pass"
  env:
    MYSQL_USER: "papermerge"
    MYSQL_DATABASE: "papermerge-mariadb"
  fullnameOverride: papermerge-mariadb

# Enabled postgres
# ... for more options see https://github.com/nicholaswilde/helm-charts/blob/main/charts/postgres/values.yaml
postgres:
  enabled: false
  secret:
    POSTGRES_PASSWORD: "papermerge-pass"
  env:
    POSTGRES_USER: "papermerge"
    POSTGRES_DB: "papermerge-postgres"
  fullnameOverride: papermerge-postgres
