---
apiVersion: v2
appVersion: 1.14.0
version: 0.1.7
name: syncthing
description: â›” DEPRECATED A continuous file synchronization program.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/syncthing"
icon: "https://github.com/syncthing/syncthing/raw/main/assets/logo-128.png"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - sync
  - thing
  - syncronization
sources:
  - https://syncthing.net/
  - https://hub.docker.com/r/syncthing/syncthing
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Bumped tag to 1.14.0
    - Removed nginx ingress annotation
  artifacthub.io/images: |
    - name: syncthing
      image: syncthing/syncthing:1.14.0
