---
apiVersion: v2
appVersion: 1.2.18
version: 0.1.8
name: kanboard
description: â›” DEPRECATED A free and open source Kanban project management software.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/kanboard"
icon: "https://github.com/nicholaswilde/helm-charts/raw/main/images/kanboard.png"
deprecated: true
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - kanboard
  - project management
sources:
  - https://kanboard.org/
  - https://hub.docker.com/r/kanboard/kanboard
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Deprecated
  artifacthub.io/images: |
    - name: kanboard
      image: ghcr.io/kanboard/kanboard:v1.2.19
