---
apiVersion: v2
appVersion: "941c0d3"
version: 0.1.0
name: todo
description: A simple self-hosted todo manager
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/todo"
icon: "https://github.com/prologic/todo/raw/master/static/icons/android-chrome-512x512.png"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - todo
  - list
  - self-hosted
  - web
  - webapp
  - todoapp
sources:
  - https://github.com/prologic/todo
  - https://github.com/nicholaswilde/docker-todo
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Initial release.
  artifacthub.io/images: |
    - name: template
      image: ghcr.io/nicholaswilde/todo:941c0d3-ls1
