---
apiVersion: v2
appVersion: v3.11.0
version: 1.1.0
name: code-server
description: Run VS Code on any machine anywhere and access it in the browser.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/code-server"
icon: "https://github.com/nicholaswilde/helm-charts/raw/main/images/code-server.jpg"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - code
  - vs
  - visual studio
  - vscode
sources:
  - https://github.com/cdr/code-server
  - https://hub.docker.com/r/linuxserver/code-server
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump tag to version-v3.11.0
  artifacthub.io/images: |
    - name: code-server
      image: ghcr.io/linuxserver/code-server:version-v3.11.0
