---
apiVersion: v2
appVersion: 1.27.4
version: 0.2.2
name: cloud9
description: A complete web based IDE with terminal access
type: application
homepage: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/cloud9"
icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/cloud9.png"
dependencies:
- name: common
  version: 0.1.3
  repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - cloud9
  - ide
  - terminal
  - web
sources:
  - https://aws.amazon.com/cloud9/
  - https://github.com/c9/core
  - https://hub.docker.com/r/linuxserver/cloud9
maintainers:
  - name: Nicholas Wilde
    email: ncwilde43@gmail.com
