---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/linuxserver/cloud9
  pullPolicy: IfNotPresent
  tag: "version-1.29.2"

secret: {}
# USERNAME="" #optional
# PASSWORD="" #optional

# See more environment variables in the cloud9 documentation
# https://github.com/linuxserver/docker-cloud9#parameters
env: {}
  # TZ: "UTC"
  # PUID: "1000"
  # PGID: "1000"
  # GITURL=https://github.com/linuxserver/docker-cloud9.git #optional

service:
  port:
    port: 8000

ingress:
  enabled: false

persistence:
  code:
    enabled: false
    emptyDir: false
    mountPath: /code
    accessMode: ReadWriteOnce
    size: 1Gi
  sock:
    enabled: false
    emptyDir: false
    mountPath: /var/run/docker.sock
    accessMode: ReadWriteOnce
    size: 1Gi
