---
apiVersion: v2
appVersion: "3.00"
version: 0.2.14
name: transmission
description: A Fast, Easy, and Free BitTorrent Client.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/transmission/transmission"
icon: "https://raw.githubusercontent.com/transmission/transmission/master/web/public_html/images/webclip-icon.png"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - transmission
  - bittorrent
  - torrent
sources:
  - https://transmissionbt.com/
  - https://hub.docker.com/r/linuxserver/transmission
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Bumped tag to 3.00-r2-ls78
  artifacthub.io/images: |
    - name: transmission
      image: ghcr.io/linuxserver/transmission:3.00-r2-ls78
