apiVersion: v2
appVersion: 3.00
version: 0.2.6
name: transmission
description: A Fast, Easy, and Free BitTorrent Client.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/transmission"
icon: "https://raw.githubusercontent.com/transmission/transmission/master/web/public_html/images/webclip-icon.png"
dependencies:
- name: common
  version: ~0.1.7
  repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - transmission
  - bittorrent
  - torrent
sources:
  - https://transmissionbt.com/
  - https://hub.docker.com/r/linuxserver/transmission
maintainers:
  - name: Nicholas Wilde
    email: ncwilde43@gmail.com
