---
apiVersion: v2
appVersion: "3.51.0-r1"
version: 1.0.1
name: filezilla
description: A Helm chart for Kubernetes
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/filezilla"
icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/filezilla-logo.png"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - filezilla
  - ftp
  - sftp
  - ftps
  - client
sources:
  - https://filezilla-project.org/
  - https://github.com/linuxserver/docker-filezilla
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Update port default in values schema.
  artifacthub.io/images: |
    - name: template
      image: ghcr.io/linuxserver/filezilla:version-3.51.0-r1
