---
apiVersion: v2
appVersion: "2.7.3"
version: 0.1.24
name: smokeping
description: Keep track of your network latency.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/smokeping"
icon: "https://github.com/nicholaswilde/helm-charts/raw/main/images/smokeping.png"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - smokeping
  - network
  - latency
sources:
  - https://oss.oetiker.ch/smokeping/
  - https://hub.docker.com/r/linuxserver/smokeping
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Change tag to version-2.7.3-r5 in order to reduce the number of chart updates.
  artifacthub.io/images: |
    - name: smokeping
      image: ghcr.io/linuxserver/smokeping:version-2.7.3-r5
