{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "papermerge.fullname" . }}-data
  {{- if .Values.persistence.data.skipuninstall }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
  labels:
    {{- include "papermerge.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.data.size | quote }}
{{- if .Values.persistence.data.storageClass }}
{{- if (eq "-" .Values.persistence.data.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
{{- end }}
{{- end }}
{{- end -}}
