---
apiVersion: v2
appVersion: "2021.5.10"
version: 0.1.0
name: sickchill
description: An Automatic Video Library Manager for TV Shows
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/sickchill"
icon: "https://github.com/SickChill/SickChill/raw/master/sickchill/gui/slick/images/ico/android-chrome-256x256.png"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - sickchill
  - video
  - library
  - manager
sources:
  - https://github.com/linuxserver/docker-sickchill
  - https://github.com/SickChill/SickChill
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Initial release.
  artifacthub.io/images: |
    - name: sickchill
      image: ghcr.io/linuxserver/sickchill:2021.5.10-1-ls63
