---
apiVersion: v2
appVersion: "1.7.16"
version: 0.1.4
name: grav
description: A Fast, Simple, and Flexible, file-based Web-platform.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/grav"
icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/grav-logo.png"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - grav
  - web
  - platform
  - file
sources:
  - https://github.com/linuxserver/docker-grav
  - https://github.com/getgrav/grav/
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Change tag to version-1.7.16 to reduce number of chart releases.
  artifacthub.io/images: |
    - name: grav
      image: ghcr.io/linuxserver/grav:version-1.7.16
