---
apiVersion: v2
appVersion: 4.19.0
version: 1.0.0
name: diun
description: Docker image update notifier
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/diun"
icon: "https://raw.githubusercontent.com/crazy-max/diun/master/.res/diun.png"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - docker
  - notifier
  - notification
  - image
  - update
sources:
  - https://crazymax.dev/diun/
  - https://hub.docker.com/r/crazymax/diun
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump tag to 4.19.0
    - kind: changed
      description: Bump common to 0.1.13
    - kind: changed
      description: Simplify values.yaml
  artifacthub.io/images: |
    - name: diun
      image: ghcr.io/crazy-max/diun:4.19.0
