---
apiVersion: v2
appVersion: 1.8.14
version: 1.0.2
name: etherpad
description: A real-time collaborative editor scalable to thousands of simultaneous real time users.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/etherpad"
icon: "https://github.com/nicholaswilde/helm-charts/raw/main/images/etherpad.jpg"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
  - name: mariadb
    version: ~1.0.5
    repository: https://nicholaswilde.github.io/helm-charts/
    condition: mariadb.enabled
  - name: postgres
    version: ~0.1.0
    repository: https://nicholaswilde.github.io/helm-charts/
    condition: postgres.enabled
keywords:
  - etherpad
  - editor
  - notepad
  - pad
sources:
  - https://etherpad.org/
  - https://github.com/ether/etherpad-lite
  - https://hub.docker.com/r/nicholaswilde/etherpad
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump tag to 1.8.14
  artifacthub.io/images: |
    - name: etherpad
      image: ghcr.io/nicholaswilde/etherpad:version-1.8.14
