---
apiVersion: v2
appVersion: "3.0.2"
version: 0.1.4
name: audacity
description: An easy-to-use, multi-track audio editor and recorder
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/audacity"
icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/audacity-logo.png"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - audacity
  - music
  - recorder
  - editor
  - audio
sources:
  - https://github.com/linuxserver/docker-audacity
  - https://www.audacityteam.org/
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Change tag to version-3.0.2 to reduce the number of chart updates.
  artifacthub.io/images: |
    - name: audacity
      image: ghcr.io/linuxserver/audacity:version-3.0.2
