---
apiVersion: v2
appVersion: "0.8.2-1"
version: 1.0.2
name: doublecommander
description: A free cross platform open source file manager with two panels side by side.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/doublecommander"
icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/doublecommander-icon.png"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - doublecommander
  - file
  - manager
sources:
  - https://github.com/linuxserver/docker-doublecommander
  - https://doublecmd.sourceforge.io/
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Change tag to version-0.8.2-1 to reduce the number of chart updates.
  artifacthub.io/images: |
    - name: doublecommander
      image: ghcr.io/linuxserver/doublecommander:version-0.8.2-1
