---
apiVersion: v2
appVersion: "13.3"
version: 0.1.0
name: postgres
description: The World's Most Advanced Open Source Relational Database
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/postgres"
icon: "https://d1q6f0aelx0por.cloudfront.net/product-logos/library-postgres-logo.png"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - postgres
  - database
  - relational
sources:
  - https://www.postgresql.org/
  - https://github.com/docker-library/postgres
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Initial release.
  artifacthub.io/images: |
    - name: template
      image: postgres:13.3
