---
apiVersion: v2
appVersion: "v1.2"
version: 1.0.0
name: pixapop
description: An open-source single page application to view your photos in the easiest way possible.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/pixapop"
icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/pixapop.png"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - pixapop
  - photo
  - gallery
  - image
sources:
  - https://github.com/linuxserver/docker-pixapop
  - https://github.com/bierdok/pixapop
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Cleanup values.yaml
  artifacthub.io/images: |
    - name: pixapop
      image: ghcr.io/linuxserver/pixapop:v1.2-ls15
