---
apiVersion: v2
appVersion: "057352e8"
version: 1.0.0
name: muximux
description: A lightweight portal to view & manage your HTPC apps without having to run anything more than a PHP enabled webserver
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/muximux"
icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/muximux-icon.png"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - muximux
  - htpc
  - manage
  - portal
sources:
  - https://github.com/linuxserver/docker-muximux
  - https://github.com/mescon/Muximux
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Changed tag to version-057352e8 to reduce number of chart updates.
  artifacthub.io/images: |
    - name: muximux
      image: ghcr.io/linuxserver/muximux:version-057352e8
